# Web Scraping Lab

You will find in this notebook some scrapy exercises to practise your scraping skills.

**Tips:**

- Check the response status code for each request to ensure you have obtained the intended contennt.
- Print the response text in each request to understand the kind of info you are getting and its format.
- Check for patterns in the response text to extract the data/info requested in each question.
- Visit each url and take a look at its source through Chrome DevTools. You'll need to identify the html tags, special class names etc. used for the html content you are expected to extract.

- [Requests library](http://docs.python-requests.org/en/master/#the-user-guide) documentation 
- [Beautiful Soup Doc](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Urllib](https://docs.python.org/3/library/urllib.html#module-urllib)
- [re lib](https://docs.python.org/3/library/re.html)
- [lxml lib](https://lxml.de/)
- [Scrapy](https://scrapy.org/)
- [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [HTML basics](http://www.simplehtmlguide.com/cheatsheet.php)
- [CSS basics](https://www.cssbasics.com/#page_start)

#### Below are the libraries and modules you may need. `requests`,  `BeautifulSoup` and `pandas` are imported for you. If you prefer to use additional libraries feel free to uncomment them.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
# from pprint import pprint
# from lxml import html
# from lxml.html import fromstring
import urllib.request
# from urllib.request import urlopen
# import random
import re
# import scrapy

#### Download, parse (using BeautifulSoup), and print the content from the Trending Developers page from GitHub:

In [273]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/developers'

In [274]:
#your code
response = requests.get(url)
response

In [275]:
content_git = response.content

In [276]:
soup = BeautifulSoup(content_git, "lxml")

#### Display the names of the trending developers retrieved in the previous step.

Your output should be a Python list of developer names. Each name should not contain any html tag.

**Instructions:**

1. Find out the html tag and class names used for the developer names. You can achieve this using Chrome DevTools.

1. Use BeautifulSoup to extract all the html elements that contain the developer names.

1. Use string manipulation techniques to replace whitespaces and linebreaks (i.e. `\n`) in the *text* of each html element. Use a list to store the clean names.

1. Print the list of names.

Your output should look like below:

```
['trimstray (@trimstray)',
 'joewalnes (JoeWalnes)',
 'charlax (Charles-AxelDein)',
 'ForrestKnight (ForrestKnight)',
 'revery-ui (revery-ui)',
 'alibaba (Alibaba)',
 'Microsoft (Microsoft)',
 'github (GitHub)',
 'facebook (Facebook)',
 'boazsegev (Bo)',
 'google (Google)',
 'cloudfetch',
 'sindresorhus (SindreSorhus)',
 'tensorflow',
 'apache (TheApacheSoftwareFoundation)',
 'DevonCrawford (DevonCrawford)',
 'ARMmbed (ArmMbed)',
 'vuejs (vuejs)',
 'fastai (fast.ai)',
 'QiShaoXuan (Qi)',
 'joelparkerhenderson (JoelParkerHenderson)',
 'torvalds (LinusTorvalds)',
 'CyC2018',
 'komeiji-satori (神楽坂覚々)',
 'script-8']
 ```

In [16]:
#your code

names_soup = soup.select('h1[class="h3 lh-condensed"] > a')
names = [element.text.strip() for element in names_soup]
names

['Amin Alaee',
 'Stephen Celis',
 'RangiLyu',
 'Shuhei Kadowaki',
 'Bram Gerritsen',
 'Bryan C Guner',
 'Adam Johnson',
 'Stefan Prodan',
 'Andrew Kane',
 'Alon Zakai',
 'Ha Thach',
 'Alex Gaynor',
 'Aleksandr Statciuk',
 'Adam Bradley',
 'MichaIng',
 'Joe Tsai',
 'J. Nick Koston',
 'Anton Sviridov',
 'Michael Lynch',
 'chencheng (云谦)',
 'BIGTREETECH',
 'Alex Page',
 'Jaco',
 '0xAX',
 'Robin Malfait']

#### Display the trending Python repositories in GitHub

The steps to solve this problem is similar to the previous one except that you need to find out the repository names instead of developer names.

In [17]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/python?since=daily'

In [19]:
#your code

response = requests.get(url)
content_git_repo = response.content
print(response)

<Response [200]>

In [21]:
soup = BeautifulSoup(content_git_repo, "lxml")

In [27]:
#your code

repos_soup = soup.select('h1[class="h3 lh-condensed"] > a')
repos = [element.text.split('/')[-1].strip() for element in repos_soup]
repos

['daily_morning',
 'stable-diffusion-webui',
 'GFPGAN',
 'Summer2023-Internships',
 'discord.py',
 'zulip',
 'torchdynamo',
 'yt-dlp',
 'paranoid_crypto',
 'MHDDoS',
 'hackingtool',
 'hoaxshell',
 'devops-exercises',
 'wpa-dictionary',
 'daily_reminder',
 'nas-tools',
 'awesome-python',
 'sherlock',
 'blackbird',
 'MoeGoe',
 'txt2imghd',
 'yfinance',
 'rich',
 'PyPhisher',
 'VNext']

#### Display all the image links from Walt Disney wikipedia page

In [30]:
# This is the url you will scrape in this exercise
url_wikipedia = 'https://en.wikipedia.org/wiki/Walt_Disney'

In [52]:
#your code

response_wikipedia = requests.get(url_wikipedia)
content_wikipedia = response_wikipedia.content
print(response_wikipedia)

<Response [200]>

In [53]:
soup_wikipedia = BeautifulSoup(content_wikipedia, 'lxml')

In [86]:
select_images = soup_wikipedia.select('a[class="image"]')
select_images

[<a class="image" href="/wiki/File:Walt_Disney_1946.JPG"><img alt="Walt Disney 1946.JPG" data-file-height="675" data-file-width="450" decoding="async" height="330" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/220px-Walt_Disney_1946.JPG" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/330px-Walt_Disney_1946.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/440px-Walt_Disney_1946.JPG 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_1942_signature.svg"><img alt="Walt Disney 1942 signature.svg" data-file-height="218" data-file-width="585" decoding="async" height="56" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/150px-Walt_Disney_1942_signature.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/225px-Walt_Disney_1942_signature.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/300px-Walt_Disney_1942_signature.svg.png 2x" width="150"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg"><img alt="Pale yellow wooden house with brown trim surrounded by white picket fence" class="thumbimage" data-file-height="1080" data-file-width="1440" decoding="async" height="165" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg/220px-Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg/330px-Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg/440px-Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_envelope_ca._1921.jpg"><img alt="" class="thumbimage" data-file-height="1086" data-file-width="1576" decoding="async" height="152" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/220px-Walt_Disney_envelope_ca._1921.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/330px-Walt_Disney_envelope_ca._1921.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/440px-Walt_Disney_envelope_ca._1921.jpg 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Trolley_Troubles_poster.jpg"><img alt="A cartoon rabbit is driving a tramcar; other cartoon rabbits are in, under, on and around the car." class="thumbimage" data-file-height="1600" data-file-width="1202" decoding="async" height="226" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Trolley_Troubles_poster.jpg/170px-Trolley_Troubles_poster.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Trolley_Troubles_poster.jpg/255px-Trolley_Troubles_poster.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Trolley_Troubles_poster.jpg/340px-Trolley_Troubles_poster.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Steamboat-willie.jpg"><img alt="A cartoon mouse is operating a ship's steering wheel" class="thumbimage" data-file-height="267" data-file-width="373" decoding="async" height="122" src="//upload.wikimedia.org/wikipedia/en/thumb/4/4e/Steamboat-willie.jpg/170px-Steamboat-willie.jpg" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4e/Steamboat-willie.jpg/255px-Steamboat-willie.jpg 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4e/Steamboat-willie.jpg/340px-Steamboat-willie.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_1935.jpg"><img alt="" class="thumbimage" data-file-height="4683" data-file-width="6357" decoding="async" height="125" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/57/Walt_Disney_1935.jpg/170px-Walt_Disney_1935.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/57/Walt_Disney_1935.jpg/255px-Walt_Disney_1935.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/57/Walt_Disney_1935.jpg/340px-Walt_Disney_1935.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_Snow_white_1937_trailer_screenshot_(13).jpg"><img alt="Walt Disney sits in front of a set of models of the seven dwarfs" class="thumbimage" data-file-height="388" data-file-width="500" decoding="async" height="171" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/220px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/330px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/440px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Disney_drawing_goofy.jpg"><img alt="" class="thumbimage" data-file-height="770" data-file-width="600" decoding="async" height="218" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/170px-Disney_drawing_goofy.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/255px-Disney_drawing_goofy.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/340px-Disney_drawing_goofy.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:WaltDisneyplansDisneylandDec1954.jpg"><img alt="" class="thumbimage" data-file-height="2417" data-file-width="2723" decoding="async" height="195" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/220px-WaltDisneyplansDisneylandDec1954.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/330px-WaltDisneyplansDisneylandDec1954.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/440px-WaltDisneyplansDisneylandDec1954.jpg 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Walt_disney_portrait_right.jpg"><img alt="" class="thumbimage" data-file-height="902" data-file-width="667" decoding="async" height="230" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/170px-Walt_disney_portrait_right.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/255px-Walt_disney_portrait_right.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/340px-Walt_disney_portrait_right.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:DisneySchiphol1951.jpg"><img alt="" class="thumbimage" data-file-height="2493" data-file-width="3247" decoding="async" height="169" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/220px-DisneySchiphol1951.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/330px-DisneySchiphol1951.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/440px-DisneySchiphol1951.jpg 2x" width="220"/></a>,
 <a class="image" href="/wiki/File:Walt_Disney_Grave.JPG"><img alt="A gravestone inscribed 'Walter Elias Disney', 'Lillian Bounds Disney', 'Robert B. Brown', Sharon Disney Brown Lund ashes scattered in paradise'" class="thumbimage" data-file-height="1700" data-file-width="1400" decoding="async" height="206" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/170px-Walt_Disney_Grave.JPG" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/255px-Walt_Disney_Grave.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/340px-Walt_Disney_Grave.JPG 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Roy_O._Disney_with_Company_at_Press_Conference.jpg"><img alt="" class="thumbimage" data-file-height="275" data-file-width="220" decoding="async" height="213" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Roy_O._Disney_with_Company_at_Press_Conference.jpg/170px-Roy_O._Disney_with_Company_at_Press_Conference.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/2/2d/Roy_O._Disney_with_Company_at_Press_Conference.jpg 1.5x" width="170"/></a>,
 <a class="image" href="/wiki/File:Disney_Oscar_1953_(cropped).jpg"><img alt="A black and white photograph of Walt Disney standing, holding an Academy Award." class="thumbimage" data-file-height="1214" data-file-width="841" decoding="async" height="245" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Disney_Oscar_1953_%28cropped%29.jpg/170px-Disney_Oscar_1953_%28cropped%29.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Disney_Oscar_1953_%28cropped%29.jpg/255px-Disney_Oscar_1953_%28cropped%29.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Disney_Oscar_1953_%28cropped%29.jpg/340px-Disney_Oscar_1953_%28cropped%29.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Disney1968.jpg"><img alt="A portrait of Disney with cartoon representations of different nationalities on a 6 cent US stamp" class="thumbimage" data-file-height="736" data-file-width="483" decoding="async" height="259" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/170px-Disney1968.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/255px-Disney1968.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/340px-Disney1968.jpg 2x" width="170"/></a>,
 <a class="image" href="/wiki/File:Disneyland_Resort_logo.svg"><img alt="Disneyland Resort logo.svg" data-file-height="66" data-file-width="267" decoding="async" height="33" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Disneyland_Resort_logo.svg/135px-Disneyland_Resort_logo.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Disneyland_Resort_logo.svg/203px-Disneyland_Resort_logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Disneyland_Resort_logo.svg/270px-Disneyland_Resort_logo.svg.png 2x" width="135"/></a>,
 <a class="image" href="/wiki/File:Animation_disc.svg"><img alt="icon" data-file-height="28" data-file-width="30" decoding="async" height="19" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/20px-Animation_disc.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/31px-Animation_disc.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/41px-Animation_disc.svg.png 2x" width="20"/></a>,
 <a class="image" href="/wiki/File:Magic_Kingdom_castle.jpg"><img alt="icon" data-file-height="1545" data-file-width="1262" decoding="async" height="19" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Magic_Kingdom_castle.jpg/15px-Magic_Kingdom_castle.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Magic_Kingdom_castle.jpg/24px-Magic_Kingdom_castle.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Magic_Kingdom_castle.jpg/31px-Magic_Kingdom_castle.jpg 2x" width="15"/></a>,
 <a class="image" href="/wiki/File:Blank_television_set.svg"><img alt="icon" data-file-height="92" data-file-width="138" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/21px-Blank_television_set.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/32px-Blank_television_set.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/42px-Blank_television_set.svg.png 2x" width="21"/></a>]

In [87]:
select_images[0]['href']

'/wiki/File:Walt_Disney_1946.JPG'

In [88]:
len(select_images)

20

In [89]:
link_images = [image['href'] for image in select_images if image['href']]
link_images

['/wiki/File:Walt_Disney_1946.JPG',
 '/wiki/File:Walt_Disney_1942_signature.svg',
 '/wiki/File:Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg',
 '/wiki/File:Walt_Disney_envelope_ca._1921.jpg',
 '/wiki/File:Trolley_Troubles_poster.jpg',
 '/wiki/File:Steamboat-willie.jpg',
 '/wiki/File:Walt_Disney_1935.jpg',
 '/wiki/File:Walt_Disney_Snow_white_1937_trailer_screenshot_(13).jpg',
 '/wiki/File:Disney_drawing_goofy.jpg',
 '/wiki/File:WaltDisneyplansDisneylandDec1954.jpg',
 '/wiki/File:Walt_disney_portrait_right.jpg',
 '/wiki/File:DisneySchiphol1951.jpg',
 '/wiki/File:Walt_Disney_Grave.JPG',
 '/wiki/File:Roy_O._Disney_with_Company_at_Press_Conference.jpg',
 '/wiki/File:Disney_Oscar_1953_(cropped).jpg',
 '/wiki/File:Disney1968.jpg',
 '/wiki/File:Disneyland_Resort_logo.svg',
 '/wiki/File:Animation_disc.svg',
 '/wiki/File:Magic_Kingdom_castle.jpg',
 '/wiki/File:Blank_television_set.svg']

#### Retrieve an arbitary Wikipedia page of "Python" and create a list of links on that page

In [83]:
# This is the url you will scrape in this exercise
url_python ='https://en.wikipedia.org/wiki/Python'

In [84]:
#your code

response_python = requests.get(url_python)
content_python = response_python.content
print(response_python)

<Response [200]>

In [85]:
soup_python = BeautifulSoup(content_python, 'lxml')

In [91]:
select_links = soup_python.select('div[class=mw-parser-output] > ul > li > a')
select_links

[<a href="/wiki/Pythonidae" title="Pythonidae">Pythonidae</a>,
 <a href="/wiki/Python_(mythology)" title="Python (mythology)">Python (mythology)</a>,
 <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python (programming language)</a>,
 <a href="/wiki/CMU_Common_Lisp" title="CMU Common Lisp">CMU Common Lisp</a>,
 <a href="/wiki/PERQ#PERQ_3" title="PERQ">PERQ 3</a>,
 <a href="/wiki/Python_of_Aenus" title="Python of Aenus">Python of Aenus</a>,
 <a href="/wiki/Python_(painter)" title="Python (painter)">Python (painter)</a>,
 <a href="/wiki/Python_of_Byzantium" title="Python of Byzantium">Python of Byzantium</a>,
 <a href="/wiki/Python_of_Catana" title="Python of Catana">Python of Catana</a>,
 <a href="/wiki/Python_Anghelo" title="Python Anghelo">Python Anghelo</a>,
 <a href="/wiki/Python_(Efteling)" title="Python (Efteling)">Python (Efteling)</a>,
 <a href="/wiki/Python_(Busch_Gardens_Tampa_Bay)" title="Python (Busch Gardens Tampa Bay)">Python (Busch Gardens Tampa Bay)</a>,
 <a href="/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)" title="Python (Coney Island, Cincinnati, Ohio)">Python (Coney Island, Cincinnati, Ohio)</a>,
 <a href="/wiki/Python_(automobile_maker)" title="Python (automobile maker)">Python (automobile maker)</a>,
 <a href="/wiki/Python_(Ford_prototype)" title="Python (Ford prototype)">Python (Ford prototype)</a>,
 <a href="/wiki/Python_(missile)" title="Python (missile)">Python (missile)</a>,
 <a href="/wiki/Python_(nuclear_primary)" title="Python (nuclear primary)">Python (nuclear primary)</a>,
 <a href="/wiki/Colt_Python" title="Colt Python">Colt Python</a>,
 <a href="/wiki/Python_(codename)" title="Python (codename)">Python (codename)</a>,
 <a href="/wiki/Python_(film)" title="Python (film)"><i>Python</i> (film)</a>,
 <a href="/wiki/Monty_Python" title="Monty Python">Monty Python</a>,
 <a href="/wiki/Timon_of_Phlius" title="Timon of Phlius">Timon of Phlius</a>,
 <a href="/wiki/Cython" title="Cython">Cython</a>,
 <a href="/wiki/Pithon" title="Pithon">Pithon</a>]

In [92]:
links = [link['href'] for link in select_links if link['href']]
links

['/wiki/Pythonidae',
 '/wiki/Python_(mythology)',
 '/wiki/Python_(programming_language)',
 '/wiki/CMU_Common_Lisp',
 '/wiki/PERQ#PERQ_3',
 '/wiki/Python_of_Aenus',
 '/wiki/Python_(painter)',
 '/wiki/Python_of_Byzantium',
 '/wiki/Python_of_Catana',
 '/wiki/Python_Anghelo',
 '/wiki/Python_(Efteling)',
 '/wiki/Python_(Busch_Gardens_Tampa_Bay)',
 '/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)',
 '/wiki/Python_(automobile_maker)',
 '/wiki/Python_(Ford_prototype)',
 '/wiki/Python_(missile)',
 '/wiki/Python_(nuclear_primary)',
 '/wiki/Colt_Python',
 '/wiki/Python_(codename)',
 '/wiki/Python_(film)',
 '/wiki/Monty_Python',
 '/wiki/Timon_of_Phlius',
 '/wiki/Cython',
 '/wiki/Pithon']

#### Number of Titles that have changed in the United States Code since its last release point

In [94]:
# This is the url you will scrape in this exercise
url_usa = 'http://uscode.house.gov/download/download.shtml'

In [ ]:
#your code

response_usa = requests.get(url_usa)
content_usa = response_usa.content
print(response_usa)

In [97]:
soup_usa = BeautifulSoup(content_usa, 'lxml')

In [98]:
select_titles = soup_usa.select('div[class=usctitlechanged]')
select_titles

[<div class="usctitlechanged" id="us/usc/t2">

           Title 2 - The Congress

         </div>,
 <div class="usctitlechanged" id="us/usc/t5">

           Title 5 - Government Organization and Employees <span class="footnote"><a class="fn" href="#fn">٭</a></span>
 </div>,
 <div class="usctitlechanged" id="us/usc/t10">

           Title 10 - Armed Forces <span class="footnote"><a class="fn" href="#fn">٭</a></span>
 </div>,
 <div class="usctitlechanged" id="us/usc/t28">

           Title 28 - Judiciary and Judicial Procedure <span class="footnote"><a class="fn" href="#fn">٭</a></span>
 </div>,
 <div class="usctitlechanged" id="us/usc/t38">

           Title 38 - Veterans' Benefits <span class="footnote"><a class="fn" href="#fn">٭</a></span>
 </div>]

In [99]:
len(select_titles)

5

#### A Python list with the top ten FBI's Most Wanted names

In [100]:
# This is the url you will scrape in this exercise
url_fbi = 'https://www.fbi.gov/wanted/topten'

In [101]:
#your code

response_fbi = requests.get(url_fbi)
content_fbi = response_fbi.content
print(response_fbi)

<Response [200]>

In [102]:
soup_fbi = BeautifulSoup(content_fbi, 'lxml')

In [106]:
select_fbi = soup_fbi.select('h3[class=title] > a')
select_fbi

[<a href="https://www.fbi.gov/wanted/topten/alexis-flores">ALEXIS FLORES</a>,
 <a href="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez">JOSE RODOLFO VILLARREAL-HERNANDEZ</a>,
 <a href="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias">YULAN ADONAY ARCHAGA CARIAS</a>,
 <a href="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel">BHADRESHKUMAR CHETANBHAI PATEL</a>,
 <a href="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas">OMAR ALEXANDER CARDENAS</a>,
 <a href="https://www.fbi.gov/wanted/topten/alejandro-castillo">ALEJANDRO ROSALES CASTILLO</a>,
 <a href="https://www.fbi.gov/wanted/topten/ruja-ignatova">RUJA IGNATOVA</a>,
 <a href="https://www.fbi.gov/wanted/topten/jason-derek-brown">JASON DEREK BROWN</a>,
 <a href="https://www.fbi.gov/wanted/topten/arnoldo-jimenez">ARNOLDO JIMENEZ</a>,
 <a href="https://www.fbi.gov/wanted/topten/rafael-caro-quintero">RAFAEL CARO-QUINTERO</a>]

In [107]:
names = [element.text for element in select_fbi]
names

['ALEXIS FLORES',
 'JOSE RODOLFO VILLARREAL-HERNANDEZ',
 'YULAN ADONAY ARCHAGA CARIAS',
 'BHADRESHKUMAR CHETANBHAI PATEL',
 'OMAR ALEXANDER CARDENAS',
 'ALEJANDRO ROSALES CASTILLO',
 'RUJA IGNATOVA',
 'JASON DEREK BROWN',
 'ARNOLDO JIMENEZ',
 'RAFAEL CARO-QUINTERO']

####  20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe

In [108]:
# This is the url you will scrape in this exercise
url_emsc = 'https://www.emsc-csem.org/Earthquake/'

In [119]:
# your code

df_emsc = pd.read_html(url_emsc)[3]
df_emsc

   CitizenResponse                                  \
     12345678910» 12345678910».1 12345678910».2
0              NaN             NaN             NaN
1              NaN             NaN             NaN
2              NaN             NaN             NaN
3              NaN             NaN             NaN
4              NaN             NaN             NaN
5              NaN             NaN             NaN
6              NaN             NaN             NaN
7              NaN             NaN             NaN
8              NaN             NaN             NaN
9               60             NaN              IV
10             NaN             NaN             NaN
11             NaN             NaN             NaN
12             NaN             NaN             NaN
13             NaN             NaN             NaN
14             NaN             NaN             NaN
15             NaN             NaN             NaN
16             NaN             NaN             NaN
17             NaN             NaN             NaN
18             NaN             NaN             NaN
19             NaN             NaN             NaN
20             NaN             NaN             NaN
21             NaN             NaN             NaN
22             NaN             NaN             NaN
23             NaN             NaN             NaN
24             NaN             NaN             NaN
25             NaN             NaN             NaN
26             NaN             NaN             NaN
27             NaN             NaN             NaN
28             NaN             NaN             NaN
29             NaN             NaN             NaN
30             NaN             NaN             NaN
31             NaN             NaN             NaN
32             NaN             NaN             NaN
33             NaN             NaN             NaN
34             NaN             NaN             NaN
35             NaN             NaN             NaN
36             NaN             NaN               F
37             NaN             NaN             NaN
38             NaN             NaN             NaN
39             NaN             NaN             NaN
40             NaN             NaN             NaN
41             NaN             NaN             NaN
42             NaN             NaN             NaN
43             NaN             NaN             NaN
44             NaN             NaN             NaN
45               1             NaN               F
46             NaN             NaN             NaN
47             NaN             NaN             NaN
48             NaN             NaN             NaN
49             NaN             NaN             NaN
50             NaN             NaN             NaN
51   12345678910»   12345678910»   12345678910»
52             NaN             NaN             NaN

                       Date & Time UTC Latitude degrees                  \
                         12345678910»    12345678910» 12345678910».1
0       2022-08-28 17:49:38.046min ago             8.75               N
1       2022-08-28 17:42:21.053min ago            31.41               S
2       2022-08-28 17:42:16.453min ago            17.96               N
3       2022-08-28 17:41:25.054min ago             1.61               N
4   2022-08-28 17:33:10.11hr 02min ago            38.84               N
5   2022-08-28 17:24:39.01hr 10min ago             2.44               S
6   2022-08-28 17:08:09.41hr 27min ago            19.12               N
7   2022-08-28 17:04:39.61hr 30min ago             1.04               S
8   2022-08-28 16:58:49.21hr 36min ago             6.63               N
9   2022-08-28 16:50:50.01hr 44min ago            43.05               N
10  2022-08-28 15:54:52.02hr 40min ago             8.73               S
11  2022-08-28 15:52:13.42hr 43min ago            17.95               N
12  2022-08-28 15:43:23.42hr 52min ago            33.93               N
13  2022-08-28 15:13:19.03hr 22min ago             1.47               S
14  2022-08-28 15:12:00.93hr 23min ago            17.95               N
15  2022-08-28 15:08:48.03hr 26min ago            19.05               N
16  2022-08-28 15:08:01.43hr 27min ago            37.83               N
17  2022-08-28 15:02:20.03hr 33min ago            28.74               S
18  2022-08-28 14:54:25.73hr 41min ago            19.23               N
19  2022-08-28 14:44:00.03hr 51min ago            21.30               S
20  2022-08-28 14:35:00.04hr 00min ago             8.62               N
21  2022-08-28 14:24:09.04hr 11min ago            21.13               S
22  2022-08-28 14:23:50.64hr 11min ago            28.64               N
23  2022-08-28 14:12:59.44hr 22min ago            38.57               N
24  2022-08-28 14:08:15.84hr 27min ago            19.24               N
25  2022-08-28 13:49:16.04hr 46min ago             0.66               N
26  2022-08-28 13:47:37.04hr 48min ago            21.29               S
27  2022-08-28 13:43:13.04hr 52min ago             0.20               N
28  2022-08-28 13:37:51.94hr 57min ago             1.16               N
29  2022-08-28 13:26:53.35hr 08min ago            18.48               N
30  2022-08-28 13:24:53.85hr 10min ago            38.59               N
31  2022-08-28 13:24:01.95hr 11min ago            38.42               S
32  2022-08-28 13:21:11.25hr 14min ago            21.38               S
33  2022-08-28 13:11:44.05hr 23min ago            22.68               S
34  2022-08-28 13:10:18.35hr 25min ago            38.12               N
35  2022-08-28 13:04:10.95hr 31min ago            38.17               N
36  2022-08-28 13:03:22.65hr 32min ago            38.43               N
37  2022-08-28 12:56:23.85hr 39min ago            19.18               N
38  2022-08-28 12:45:45.05hr 49min ago             8.87               S
39  2022-08-28 12:30:29.06hr 05min ago             9.30               S
40  2022-08-28 12:19:12.16hr 16min ago            51.71               N
41  2022-08-28 12:15:39.06hr 19min ago            20.92               N
42  2022-08-28 12:06:58.06hr 28min ago            23.82               S
43  2022-08-28 12:06:25.06hr 29min ago            28.40               S
44  2022-08-28 12:02:24.76hr 33min ago            19.18               N
45  2022-08-28 11:59:20.06hr 36min ago             2.94               S
46  2022-08-28 11:33:19.07hr 02min ago             1.34               S
47  2022-08-28 11:32:27.97hr 03min ago            61.03               N
48  2022-08-28 11:25:00.07hr 10min ago            19.91               N
49  2022-08-28 11:20:54.97hr 14min ago            39.04               N
50                                 NaN              NaN             NaN
51                       12345678910»    12345678910»   12345678910»
52                                 NaN              NaN             NaN

   Longitude degrees                       Depth km        Mag [+]  \
       12345678910» 12345678910».1  12345678910»  12345678910»
0              82.90               W             23              M
1              71.62               W             43              M
2              67.02               W              9             Md
3             123.16               E             10              M
4             122.78               W              2             Md
5             122.69               E             21              M
6             155.41               W             31             Ml
7              98.65               E             10             Mw
8             126.70               E            179             mb
9              18.23               E              5             ML
10            116.31               E             87              M
11             67.01               W              9             Md
12             97.31               W             10             ML
13            119.35               E             10              M
14             67.01               W              8             Md
15             66.82               W             35             ML
16             21.40               E             20             ML
17             71.48               W             15              M
18            155.41               W             35             ML
19             69.72               W             51              M
20            127.04               E              5              M
21             68.94               W            114              M
22             17.77               W             14             ML
23              0.74               W             14             ML
24            155.38               W             33             Md
25            125.07               E             19              M
26             68.61               W            126              M
27             98.90               E             28              M
28             91.74               E             10             mb
29             66.41               W             25             Md
30              0.77               W              6             ML
31            175.96               E             82              M
32            178.89               W            578             Mw
33             68.85               W            104              M
34             38.48               E             11             ML
35            118.01               W              5             ML
36              0.86               W             60             ML
37            155.47               W             32             Ml
38            118.72               E             10              M
39            110.35               E             10              M
40            160.18               E             30             mb
41            122.77               E             32              M
42             66.88               W            209              M
43             68.53               W             31              M
44            155.46               W             34             Md
45            119.41               E             10              M
46            120.40               E             10              M
47            149.39               W             33             ML
48             70.38               W             30              M
49             43.67               E              0             ML
50               NaN             NaN            NaN            NaN
51     12345678910»   12345678910»  12345678910»  12345678910»
52               NaN             NaN            NaN            NaN

   Region name [+]                  Last update [-] Unnamed: 12_level_0
     12345678910»                    12345678910»       12345678910»
0              2.9  PANAMA-COSTA RICA BORDER REGION    2022-08-28 17:50
1              2.8         OFFSHORE COQUIMBO, CHILE    2022-08-28 17:59
2              2.1               PUERTO RICO REGION    2022-08-28 17:53
3              4.5    MINAHASA, SULAWESI, INDONESIA    2022-08-28 17:50
4              2.1              NORTHERN CALIFORNIA    2022-08-28 17:34
5              3.9              SULAWESI, INDONESIA    2022-08-28 17:30
6              2.2         ISLAND OF HAWAII, HAWAII    2022-08-28 17:13
7              4.7  KEP. MENTAWAI REGION, INDONESIA    2022-08-28 17:58
8              4.5            MINDANAO, PHILIPPINES    2022-08-28 17:34
9              3.3           BOSNIA AND HERZEGOVINA    2022-08-28 17:46
10             2.7         LOMBOK REGION, INDONESIA    2022-08-28 16:15
11             2.4               PUERTO RICO REGION    2022-08-28 16:36
12             2.5                         OKLAHOMA    2022-08-28 16:15
13             3.0              SULAWESI, INDONESIA    2022-08-28 15:30
14             2.8               PUERTO RICO REGION    2022-08-28 16:01
15             3.1               PUERTO RICO REGION    2022-08-28 16:22
16             2.4                  SOUTHERN GREECE    2022-08-28 15:51
17             2.9          OFFSHORE ATACAMA, CHILE    2022-08-28 15:12
18             2.6         ISLAND OF HAWAII, HAWAII    2022-08-28 15:03
19             2.7                  TARAPACA, CHILE    2022-08-28 14:57
20             3.1        PHILIPPINE ISLANDS REGION    2022-08-28 14:50
21             3.1                  TARAPACA, CHILE    2022-08-28 14:35
22             1.5     CANARY ISLANDS, SPAIN REGION    2022-08-28 15:15
23             2.0                            SPAIN    2022-08-28 14:52
24             2.1         ISLAND OF HAWAII, HAWAII    2022-08-28 14:11
25             3.4                      MOLUCCA SEA    2022-08-28 13:55
26             3.0               ANTOFAGASTA, CHILE    2022-08-28 14:09
27             3.8           NIAS REGION, INDONESIA    2022-08-28 13:50
28             4.4               NORTH INDIAN OCEAN    2022-08-28 13:54
29             3.0                      PUERTO RICO    2022-08-28 14:12
30             2.3                            SPAIN    2022-08-28 13:34
31             3.1      NORTH ISLAND OF NEW ZEALAND    2022-08-28 13:30
32             5.1                      FIJI REGION    2022-08-28 14:08
33             3.4               ANTOFAGASTA, CHILE    2022-08-28 13:21
34             2.2                   EASTERN TURKEY    2022-08-28 13:38
35             3.1                           NEVADA    2022-08-28 13:46
36             3.0                            SPAIN    2022-08-28 13:28
37             2.1         ISLAND OF HAWAII, HAWAII    2022-08-28 13:01
38             3.5        SUMBAWA REGION, INDONESIA    2022-08-28 12:55
39             3.7         SOUTH OF JAVA, INDONESIA    2022-08-28 12:35
40             4.8      OFF EAST COAST OF KAMCHATKA    2022-08-28 13:14
41             3.7    BATAN ISL REGION, PHILIPPINES    2022-08-28 12:25
42             3.4                 JUJUY, ARGENTINA    2022-08-28 12:16
43             3.0              LA RIOJA, ARGENTINA    2022-08-28 12:16
44             2.0         ISLAND OF HAWAII, HAWAII    2022-08-28 12:05
45             2.9              SULAWESI, INDONESIA    2022-08-28 12:05
46             2.7              SULAWESI, INDONESIA    2022-08-28 11:40
47             2.4                  SOUTHERN ALASKA    2022-08-28 12:23
48             3.0        DOMINICAN REPUBLIC REGION    2022-08-28 16:50
49             2.5                   EASTERN TURKEY    2022-08-28 12:20
50             NaN                              NaN                 NaN
51   12345678910»                    12345678910»       12345678910»
52             NaN                              NaN                 NaN

In [113]:
df_emsc.columns

MultiIndex([(    'CitizenResponse',   '12345678910»'),
            (    'CitizenResponse', '12345678910».1'),
            (    'CitizenResponse', '12345678910».2'),
            (    'Date & Time UTC',   '12345678910»'),
            (   'Latitude degrees',   '12345678910»'),
            (   'Latitude degrees', '12345678910».1'),
            (  'Longitude degrees',   '12345678910»'),
            (  'Longitude degrees', '12345678910».1'),
            (           'Depth km',   '12345678910»'),
            (            'Mag [+]',   '12345678910»'),
            (    'Region name [+]',   '12345678910»'),
            (    'Last update [-]',   '12345678910»'),
            ('Unnamed: 12_level_0',   '12345678910»')],
           )

In [125]:
df = df_emsc[['Date & Time UTC','Latitude degrees','Longitude degrees', 'Last update [-]']]
df = df[0:21].rename(columns = {'Last update [-]' : 'Region Name'})
df

                       Date & Time UTC Latitude degrees                  \
                         12345678910»    12345678910» 12345678910».1
0       2022-08-28 17:49:38.046min ago             8.75               N
1       2022-08-28 17:42:21.053min ago            31.41               S
2       2022-08-28 17:42:16.453min ago            17.96               N
3       2022-08-28 17:41:25.054min ago             1.61               N
4   2022-08-28 17:33:10.11hr 02min ago            38.84               N
5   2022-08-28 17:24:39.01hr 10min ago             2.44               S
6   2022-08-28 17:08:09.41hr 27min ago            19.12               N
7   2022-08-28 17:04:39.61hr 30min ago             1.04               S
8   2022-08-28 16:58:49.21hr 36min ago             6.63               N
9   2022-08-28 16:50:50.01hr 44min ago            43.05               N
10  2022-08-28 15:54:52.02hr 40min ago             8.73               S
11  2022-08-28 15:52:13.42hr 43min ago            17.95               N
12  2022-08-28 15:43:23.42hr 52min ago            33.93               N
13  2022-08-28 15:13:19.03hr 22min ago             1.47               S
14  2022-08-28 15:12:00.93hr 23min ago            17.95               N
15  2022-08-28 15:08:48.03hr 26min ago            19.05               N
16  2022-08-28 15:08:01.43hr 27min ago            37.83               N
17  2022-08-28 15:02:20.03hr 33min ago            28.74               S
18  2022-08-28 14:54:25.73hr 41min ago            19.23               N
19  2022-08-28 14:44:00.03hr 51min ago            21.30               S
20  2022-08-28 14:35:00.04hr 00min ago             8.62               N

   Longitude degrees                                      Region Name
       12345678910» 12345678910».1                    12345678910»
0              82.90               W  PANAMA-COSTA RICA BORDER REGION
1              71.62               W         OFFSHORE COQUIMBO, CHILE
2              67.02               W               PUERTO RICO REGION
3             123.16               E    MINAHASA, SULAWESI, INDONESIA
4             122.78               W              NORTHERN CALIFORNIA
5             122.69               E              SULAWESI, INDONESIA
6             155.41               W         ISLAND OF HAWAII, HAWAII
7              98.65               E  KEP. MENTAWAI REGION, INDONESIA
8             126.70               E            MINDANAO, PHILIPPINES
9              18.23               E           BOSNIA AND HERZEGOVINA
10            116.31               E         LOMBOK REGION, INDONESIA
11             67.01               W               PUERTO RICO REGION
12             97.31               W                         OKLAHOMA
13            119.35               E              SULAWESI, INDONESIA
14             67.01               W               PUERTO RICO REGION
15             66.82               W               PUERTO RICO REGION
16             21.40               E                  SOUTHERN GREECE
17             71.48               W          OFFSHORE ATACAMA, CHILE
18            155.41               W         ISLAND OF HAWAII, HAWAII
19             69.72               W                  TARAPACA, CHILE
20            127.04               E        PHILIPPINE ISLANDS REGION

#### Display the date, days, title, city, country of next 25 hackathon events as a Pandas dataframe table

In [126]:
# This is the url you will scrape in this exercise
url_hackathon ='https://mlh.io/seasons/na-2020/events'

In [128]:
#your code

response_hack = requests.get(url_hackathon)
content_hack = response_hack.content
print(response_hack)

<Response [200]>

In [129]:
soup_hack = BeautifulSoup(content_hack, 'lxml')

In [138]:
select_name = soup_hack.select('h3[class=event-name]')
event_name = [element.text for element in select_name]
event_name

['HackMTY',
 'Citizen Hacks',
 'PennApps',
 ' Hackathon de Futuras Tecnologías ',
 'Hack the North',
 'HopHacks',
 'BigRed//Hacks',
 'HackRice',
 'SBUHacks ',
 ' ShellHacks',
 'sunhacks',
 'Kent Hack Enough',
 'MedHacks',
 'VolHacks',
 'GirlHacks',
 'GrizzHacks 4',
 'hackNY',
 'HackUMBC',
 'RamHacks',
 'HackTheU',
 'MHacks',
 'Polyhack',
 'The Pitt Challenge',
 'Dubhacks',
 'HackNC',
 'HackUIowa',
 'HackFSU',
 'HackHarvard College',
 'HackUMass VII',
 'HackRU',
 'health++',
 'MadHacks',
 'TAMU Datathon',
 'Cal Hacks',
 'DandyHacks',
 'HackGT',
 'MXHACKS VI',
 'SD Hacks',
 'TechTogether New York',
 'YHack',
 'HackGSU',
 'SquirrelHacks',
 'VandyHacks',
 'Code for Good',
 'HackPSU',
 'HackRPI',
 'HackTX',
 'HealthHacks 2019',
 'UB Hacking',
 'WHACK',
 'Hack KState',
 'HackPrinceton Fall 2019',
 'TigerHacks',
 'HackNJIT',
 'HackUTD VI',
 'Technica',
 'TeenHacks LI',
 'Lehman Hackathon (NSBESHPE)   ',
 ' BostonHacks',
 'Hack Western',
 'SB Hacks VI',
 'BullyHack',
 'cuHacking',
 'nwHacks',
 'SheHacks',
 'CruzHacks',
 'Hack Arizona',
 'UofTHacks',
 'Womxn/Hacks\t',
 'BCHacks',
 'HackDavis',
 'HackED  ',
 'HackFRee 2020',
 'Rose Hack',
 'StarterHacks',
 'BoilerMake',
 'ConUHacks',
 'CUhackit',
 'DeltaHacks',
 'MinneHack 2020',
 'PixelHacks IV',
 'QWER Hacks',
 'TAMUhack',
 'Ellehacks',
 'HackSC',
 'Hoya Hacks',
 'QHacks',
 'SwampHacks',
 'TechTogether Boston',
 'MakeHarvard',
 'McHacks',
 'HackCWRU 2020',
 'HackKU',
 'UGAHacks 5',
 'uOttaHack',
 'AuburnHacks',
 'BrickHack 6',
 'HackHer413  ',
 'Hacklahoma',
 '[email\xa0protected]',
 'Hack the Valley IIII',
 'SteelHacks',
 'VTHacks',
 'HackUNT',
 'MakeUofT',
 'TAMUmake',
 'Uncommon Hacks',
 'CalvinHacks',
 'DragonHacks',
 'HackCU VI',
 'Hacklytics  ',
 'Pearl Hacks',
 'RevolutionUC',
 'SacHacks',
 'HackMerced',
 'SLO Hacks',
 'HackTCNJ',
 'ProfHacks',
 'WiCHacks',
 'HackNYU',
 'Hacktech',
 'AthenaHacks',
 'cmd-f',
 'HackWesTX',
 'Hack Quarantine',
 'LA Hacks',
 'WinHacks',
 'HooHacks',
 'RowdyHacks',
 'Local Hack Day: Share',
 'CatHacks',
 'Citrus Hack',
 'HackDSC',
 'hack:now',
 'DistanceHacks',
 'Hack at Home',
 'TOHacks',
 'Hacklarious',
 'RU Hacks',
 'Hack the Chain',
 'hths.hacks()',
 'BackyardHacks',
 'OpenHacks',
 'RookieHacks',
 'MasseyHacks',
 'NotUniversity Hacks',
 'Same Home Different Hacks',
 'Hack Girl Summer',
 'Def Hacks Virtual',
 'Data Day Grind',
 'HackTJ']

In [140]:
select_date = soup_hack.select('p[class=event-date]')
event_date = [element.text.strip() for element in select_date]
event_date

['Aug 24th - 25th',
 'Sep 6th - 8th',
 'Sep 6th - 8th',
 'Sep 7th - 8th',
 'Sep 13th - 15th',
 'Sep 13th - 15th',
 'Sep 20th - 22nd',
 'Sep 20th - 21st',
 'Sep 20th - 21st',
 'Sep 20th - 22nd',
 'Sep 20th - 22nd',
 'Sep 27th - 29th',
 'Sep 27th - 29th',
 'Sep 27th - 29th',
 'Sep 28th - 29th',
 'Sep 28th - 29th',
 'Sep 28th - 29th',
 'Sep 28th - 29th',
 'Sep 28th - 29th',
 'Oct 5th - 6th',
 'Oct 11th - 13th',
 'Oct 11th - 12th',
 'Oct 11th - 12th',
 'Oct 12th - 13th',
 'Oct 12th - 13th',
 'Oct 12th - 13th',
 'Oct 18th - 20th',
 'Oct 18th - 20th',
 'Oct 18th - 20th',
 'Oct 19th - 20th',
 'Oct 19th - 20th',
 'Oct 19th - 20th',
 'Oct 19th - 20th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Oct 25th - 27th',
 'Nov 1st - 3rd',
 'Nov 1st - 3rd',
 'Nov 1st - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 2nd - 3rd',
 'Nov 8th - 10th',
 'Nov 8th - 10th',
 'Nov 8th - 10th',
 'Nov 9th - 10th',
 'Nov 9th - 10th',
 'Nov 9th - 10th',
 'Nov 9th - 10th',
 'Nov 15th - 16th',
 'Nov 16th - 17th',
 'Nov 22nd - 24th',
 'Jan 10th - 12th',
 'Jan 11th - 12th',
 'Jan 11th - 12th',
 'Jan 11th - 12th',
 'Jan 11th - 12th',
 'Jan 17th - 19th',
 'Jan 17th - 19th',
 'Jan 17th - 19th',
 'Jan 17th - 19th',
 'Jan 18th - 19th',
 'Jan 18th - 19th',
 'Jan 18th - 19th',
 'Jan 18th - 19th',
 'Jan 18th - 19th',
 'Jan 18th - 19th',
 'Jan 24th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 25th - 26th',
 'Jan 31st - Feb 2nd',
 'Jan 31st - Feb 2nd',
 'Jan 31st - Feb 2nd',
 'Jan 31st - Feb 2nd',
 'Jan 31st - Feb 2nd',
 'Jan 31st - Feb 2nd',
 'Feb 1st - 2nd',
 'Feb 1st - 2nd',
 'Feb 7th - 9th',
 'Feb 7th - 9th',
 'Feb 7th - 9th',
 'Feb 7th - 9th',
 'Feb 8th - 9th',
 'Feb 8th - 9th',
 'Feb 8th - 9th',
 'Feb 8th - 9th',
 'Feb 14th - 16th',
 'Feb 14th - 16th',
 'Feb 14th - 15th',
 'Feb 14th - 16th',
 'Feb 15th - 16th',
 'Feb 15th - 16th',
 'Feb 15th - 16th',
 'Feb 15th - 16th',
 'Feb 21st - 22nd',
 'Feb 22nd - 23rd',
 'Feb 22nd - 23rd',
 'Feb 22nd - 23rd',
 'Feb 22nd - 23rd',
 'Feb 22nd - 23rd',
 'Feb 22nd - 23rd',
 'Feb 28th - Mar 1st',
 'Feb 28th - Mar 1st',
 'Feb 29th - Mar 1st',
 'Feb 29th - Mar 1st',
 'Feb 29th - Mar 1st',
 'Mar 6th - 8th',
 'Mar 6th - 8th',
 'Mar 7th - 8th',
 'Mar 7th - 8th',
 'Mar 7th - 8th',
 'Mar 23rd - Apr 12th',
 'Mar 27th - 29th',
 'Mar 27th - 29th',
 'Mar 28th - 29th',
 'Mar 28th - 29th',
 'Apr 2nd - 20th',
 'Apr 4th - 5th',
 'Apr 24th - 26th',
 'Apr 24th - 26th',
 'Apr 24th - 26th',
 'May 1st - 3rd',
 'May 2nd - 3rd',
 'May 2nd - 3rd',
 'May 9th - 10th',
 'May 15th - 17th',
 'May 16th - 17th',
 'May 16th - 17th',
 'May 23rd - 24th',
 'May 23rd - 24th',
 'May 29th - 31st',
 'May 30th - 31st',
 'Jun 6th - 7th',
 'Jun 12th - 14th',
 'Jun 19th - 21st',
 'Jun 20th - 21st',
 'Jun 27th - 28th',
 'Dec 12th - 13th']

In [175]:
select_location = soup_hack.select('div[class=event-location]')
event_location = [element.text.strip(' \n').split('\n') for element in select_location]
event_location

[['Monterrey,', '          MX'],
 ['Toronto,', '          ON'],
 ['Philadelphia,', '          PA'],
 ['Torreón,', '          MX'],
 ['Waterloo,', '          ON'],
 ['Baltimore,', '          MD'],
 ['Ithaca,', '          NY'],
 ['Houston,', '          TX'],
 ['Stony Brook,', '          NY'],
 ['Miami,', '          FL'],
 ['Tempe,', '          AZ'],
 ['Kent,', '          OH'],
 ['Baltimore,', '          MD'],
 ['Knoxville,', '          TN'],
 ['Newark,', '          NJ'],
 ['Rochester,', '          MI'],
 ['New York City,', '          NY'],
 ['Baltimore,', '          MD'],
 ['Richmond,', '          VA'],
 ['Salt Lake City,', '          UT'],
 ['Ann Arbor,', '          MI'],
 ['Somerville,', '          MA'],
 ['Pittsburgh,', '          PA'],
 ['Seattle,', '          WA'],
 ['Chapel Hill,', '          NC'],
 ['Iowa City,', '          IA'],
 ['Tallahassee,', '          FL'],
 ['Cambridge,', '          MA'],
 ['Amherst,', '          MA'],
 ['New Brunswick,', '          NJ'],
 ['Stanford,', '          CA'],
 ['Madison,', '          WI'],
 ['College Station,', '          TX'],
 ['Berkeley,', '          CA'],
 ['Rochester,', '          NY'],
 ['Atlanta,', '          GA'],
 ['Mexico City,', '          MX'],
 ['La Jolla,', '          CA'],
 ['Queens,', '          NY'],
 ['New Haven,', '          CT'],
 ['Atlanta,', '          GA'],
 ['Ames,', '          IA'],
 ['Nashville,', '          TN'],
 ['Durham,', '          NC'],
 ['University Park,', '          PA'],
 ['Troy,', '          NY'],
 ['Austin,', '          TX'],
 ['Richmond,', '          VA'],
 ['Buffalo,', '          NY'],
 ['Wellesley Hills,', '          MA'],
 ['Manhattan,', '          KS'],
 ['Princeton,', '          NJ'],
 ['Columbia,', '          MO'],
 ['Newark,', '          NJ'],
 ['Richardson,', '          TX'],
 ['College Park,', '          MD'],
 ['Old Westbury,', '          NY'],
 ['Bronx,', '          NY'],
 ['Boston,', '          MA'],
 ['London,', '          ON'],
 ['Santa Barbara,', '          CA'],
 ['Starkville,', '          MS'],
 ['Ottawa,', '          ON'],
 ['Vancouver,', '          BC'],
 ['London,', '          ON'],
 ['Santa Cruz,', '          CA'],
 ['Tucson,', '          AZ'],
 ['Toronto,', '          ON'],
 ['Santa Barbara,', '          CA'],
 ['Kelowna,', '          BC'],
 ['Davis,', '          CA'],
 ['Edmonton,', '          AB'],
 ['Manalapan,', '          NJ'],
 ['Riverside,', '          CA'],
 ['Waterloo,', '          CA'],
 ['West Lafayette,', '          IN'],
 ['Montreal,', '          QC'],
 ['Clemson,', '          SC'],
 ['Hamilton,', '          ON'],
 ['Minneapolis,', '          MN'],
 ['San Jose,', '          CA'],
 ['Los Angeles,', '          CA'],
 ['College Station,', '          TX'],
 ['Toronto,', '          ON'],
 ['Los Angeles,', '          CA'],
 ['Washington,', '          DC'],
 ['Kingston,', '          ON'],
 ['Gainesville,', '          FL'],
 ['Boston,', '          MA'],
 ['Cambridge,', '          MA'],
 ['Montreal,', '          QC'],
 ['Cleveland,', '          OH'],
 ['Lawrence,', '          KS'],
 ['Athens,', '          GA'],
 ['Ottawa,', '          ON'],
 ['Auburn,', '          AL'],
 ['Rochester,', '          NY'],
 ['Amherst,', '          MA'],
 ['Norman,', '          OK'],
 ['Stony Brook,', '          NY'],
 ['Scarborough,', '          ON'],
 ['Pittsburgh,', '          PA'],
 ['Blacksburg,', '          VA'],
 ['Denton,', '          TX'],
 ['Toronto,', '          ON'],
 ['College Station,', '          TX'],
 ['Chicago,', '          IL'],
 ['Grand Rapids,', '          MI'],
 ['Philadelphia,', '          PA'],
 ['Boulder,', '          CO'],
 ['Atlanta,', '          GA'],
 ['Chapel Hill,', '          NC'],
 ['Cincinnati,', '          OH'],
 ['Sacramento,', '          CA'],
 ['Merced,', '          CA'],
 ['San Luis Obispo,', '          CA'],
 ['Ewing Township,', '          NJ'],
 ['Glassboro,', '          NJ'],
 ['Rochester,', '          NY'],
 ['Brooklyn,', '          NY'],
 ['Pasadena,', '          CA'],
 ['Los Angeles,', '          CA'],
 ['Vancouver,', '          BC'],
 ['Lubbock,', '          TX'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Windsor,', '          ON'],
 ['Charlottesville,', '          VA'],
 ['San Antonio,', '          TX'],
 ['Everywhere,', '          Worldwide'],
 ['Lexington,', '          KY'],
 ['Riverside,', '          CA'],
 ['Online,', '          North America'],
 ['Berkeley,', '          CA'],
 ['Millburn,', '          NJ'],
 ['Everywhere,', '          Worldwide'],
 ['Toronto,', '          ON'],
 ['Everywhere,', '          Worldwide'],
 ['Toronto,', '          ON'],
 ['Everywhere,', '          Worldwide'],
 ['Lincroft,', '          NJ'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Windsor,', '          ON'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Everywhere,', '          Worldwide'],
 ['Alexandria,', '          VA']]

In [182]:
event_location[0] # no puedo borrar espacios intermedios

['Monterrey,', '          MX']

In [180]:
len(event_name), len(event_date), len(event_location)

(151, 151, 151)

In [183]:
df_hack = pd.DataFrame(zip(event_name, event_date, event_location),
             columns=['Title', 'Date', 'City, Country'])

df_hack = df_hack[0:25]
df_hack

,Title,Date,"City, Country"
0,HackMTY,Aug 24th - 25th,"[Monterrey,, MX]"
1,Citizen Hacks,Sep 6th - 8th,"[Toronto,, ON]"
2,PennApps,Sep 6th - 8th,"[Philadelphia,, PA]"
3,Hackathon de Futuras Tecnologías,Sep 7th - 8th,"[Torreón,, MX]"
4,Hack the North,Sep 13th - 15th,"[Waterloo,, ON]"
5,HopHacks,Sep 13th - 15th,"[Baltimore,, MD]"
6,BigRed//Hacks,Sep 20th - 22nd,"[Ithaca,, NY]"
7,HackRice,Sep 20th - 21st,"[Houston,, TX]"
8,SBUHacks,Sep 20th - 21st,"[Stony Brook,, NY]"
9,ShellHacks,Sep 20th - 22nd,"[Miami,, FL]"
10,sunhacks,Sep 20th - 22nd,"[Tempe,, AZ]"
11,Kent Hack Enough,Sep 27th - 29th,"[Kent,, OH]"
12,MedHacks,Sep 27th - 29th,"[Baltimore,, MD]"
13,VolHacks,Sep 27th - 29th,"[Knoxville,, TN]"
14,GirlHacks,Sep 28th - 29th,"[Newark,, NJ]"
15,GrizzHacks 4,Sep 28th - 29th,"[Rochester,, MI]"
16,hackNY,Sep 28th - 29th,"[New York City,, NY]"
17,HackUMBC,Sep 28th - 29th,"[Baltimore,, MD]"
18,RamHacks,Sep 28th - 29th,"[Richmond,, VA]"
19,HackTheU,Oct 5th - 6th,"[Salt Lake City,, UT]"
20,MHacks,Oct 11th - 13th,"[Ann Arbor,, MI]"
21,Polyhack,Oct 11th - 12th,"[Somerville,, MA]"
22,The Pitt Challenge,Oct 11th - 12th,"[Pittsburgh,, PA]"
23,Dubhacks,Oct 12th - 13th,"[Seattle,, WA]"
24,HackNC,Oct 12th - 13th,"[Chapel Hill,, NC]"

#### Count number of tweets by a given Twitter account.

You will need to include a ***try/except block*** for account names not found. 
<br>***Hint:*** the program should count the number of tweets for any provided account

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/'

In [ ]:
#your code

#### Number of followers of a given twitter account

You will need to include a ***try/except block*** in case account/s name not found. 
<br>***Hint:*** the program should count the followers for any provided account

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/'

In [ ]:
#your code

#### List all language names and number of related articles in the order they appear in wikipedia.org

In [184]:
# This is the url you will scrape in this exercise
url_wiki = 'https://www.wikipedia.org/'

In [185]:
#your code

response_wiki = requests.get(url_wiki)
content_wiki = response_wiki.content
print(response_wiki)

<Response [200]>

In [186]:
soup_wiki= BeautifulSoup(content_wiki, 'lxml')

In [196]:
languages_all = soup_wiki.select('div[class=central-featured] > div.central-featured-lang > a ')
languages_all

[<a class="link-box" data-slogan="The Free Encyclopedia" href="//en.wikipedia.org/" id="js-link-box-en" title="English — Wikipedia — The Free Encyclopedia">
 <strong>English</strong>
 <small><bdi dir="ltr">6 458 000+</bdi> <span>articles</span></small>
 </a>,
 <a class="link-box" data-slogan="フリー百科事典" href="//ja.wikipedia.org/" id="js-link-box-ja" title="Nihongo — ウィキペディア — フリー百科事典">
 <strong>日本語</strong>
 <small><bdi dir="ltr">1 314 000+</bdi> <span>記事</span></small>
 </a>,
 <a class="link-box" data-slogan="La enciclopedia libre" href="//es.wikipedia.org/" id="js-link-box-es" title="Español — Wikipedia — La enciclopedia libre">
 <strong>Español</strong>
 <small><bdi dir="ltr">1 755 000+</bdi> <span>artículos</span></small>
 </a>,
 <a class="link-box" data-slogan="Свободная энциклопедия" href="//ru.wikipedia.org/" id="js-link-box-ru" title="Russkiy — Википедия — Свободная энциклопедия">
 <strong>Русский</strong>
 <small><bdi dir="ltr">1 798 000+</bdi> <span>статей</span></small>
 </a>,
 <a class="link-box" data-slogan="Die freie Enzyklopädie" href="//de.wikipedia.org/" id="js-link-box-de" title="Deutsch — Wikipedia — Die freie Enzyklopädie">
 <strong>Deutsch</strong>
 <small><bdi dir="ltr">2 667 000+</bdi> <span>Artikel</span></small>
 </a>,
 <a class="link-box" data-slogan="L’encyclopédie libre" href="//fr.wikipedia.org/" id="js-link-box-fr" title="français — Wikipédia — L’encyclopédie libre">
 <strong>Français</strong>
 <small><bdi dir="ltr">2 400 000+</bdi> <span>articles</span></small>
 </a>,
 <a class="link-box" data-slogan="L'enciclopedia libera" href="//it.wikipedia.org/" id="js-link-box-it" title="Italiano — Wikipedia — L'enciclopedia libera">
 <strong>Italiano</strong>
 <small><bdi dir="ltr">1 742 000+</bdi> <span>voci</span></small>
 </a>,
 <a class="link-box jscnconv" data-slogan="自由的百科全书 / 自由的百科全書" data-title-hans="Zhōngwén — 维基百科 — 自由的百科全书" data-title-hant="Zhōngwén — 維基百科 — 自由的百科全書" href="//zh.wikipedia.org/" id="js-link-box-zh" title="Zhōngwén — 维基百科 / 維基百科 — 自由的百科全书 / 自由的百科全書">
 <strong>中文</strong>
 <small><bdi dir="ltr">1 256 000+</bdi> <span class="jscnconv" data-hans="条目" data-hant="條目">条目 / 條目</span></small>
 </a>,
 <a class="link-box" data-slogan="A enciclopédia livre" href="//pt.wikipedia.org/" id="js-link-box-pt" title="Português — Wikipédia — A enciclopédia livre">
 <strong>Português</strong>
 <small><bdi dir="ltr">1 085 000+</bdi> <span>artigos</span></small>
 </a>,
 <a class="link-box" data-slogan="الموسوعة الحرة" href="//ar.wikipedia.org/" id="js-link-box-ar" title="Al-ʿArabīyah — ويكيبيديا — الموسوعة الحرة">
 <strong><bdi dir="rtl">العربية</bdi></strong>
 <small><bdi dir="ltr">1 159 000+</bdi> <span>مقالة</span></small>
 </a>]

In [216]:
languages = [element.text.strip().replace('\xa0',' ').split('\n') for element in languages_all]
languages

[['English', '6 458 000+ articles'],
 ['日本語', '1 314 000+ 記事'],
 ['Español', '1 755 000+ artículos'],
 ['Русский', '1 798 000+ статей'],
 ['Deutsch', '2 667 000+ Artikel'],
 ['Français', '2 400 000+ articles'],
 ['Italiano', '1 742 000+ voci'],
 ['中文', '1 256 000+ 条目 / 條目'],
 ['Português', '1 085 000+ artigos'],
 ['العربية', '1 159 000+ مقالة']]

In [221]:
pd.DataFrame(languages)

           0                     1
0    English   6 458 000+ articles
1        日本語         1 314 000+ 記事
2    Español  1 755 000+ artículos
3    Русский     1 798 000+ статей
4    Deutsch    2 667 000+ Artikel
5   Français   2 400 000+ articles
6   Italiano       1 742 000+ voci
7         中文    1 256 000+ 条目 / 條目
8  Português    1 085 000+ artigos
9    العربية      1 159 000+ مقالة

#### A list with the different kind of datasets available in data.gov.uk

In [222]:
# This is the url you will scrape in this exercise
url_uk = 'https://data.gov.uk/'

In [223]:
#your code 

response_uk = requests.get(url_uk)
content_uk = response_uk.content
print(response_uk)

<Response [200]>

In [224]:
soup_uk= BeautifulSoup(content_uk, 'lxml')

In [229]:
data_soup = soup_uk.select('div > ul > li > h3.govuk-heading-s')
data_type = [element.text for element in data_soup]
data_type

['Business and economy',
 'Crime and justice',
 'Defence',
 'Education',
 'Environment',
 'Government',
 'Government spending',
 'Health',
 'Mapping',
 'Society',
 'Towns and cities',
 'Transport',
 'Digital service performance',
 'Government reference data']

#### Top 10 languages by number of native speakers stored in a Pandas Dataframe

In [230]:
# This is the url you will scrape in this exercise
url_languages = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'

In [231]:
#your code
response_languages = requests.get(url_languages)
content_languages = response_languages.content
print(response_languages)

<Response [200]>

In [236]:
df_top = pd.read_html(url_languages)[2]
df_top = df_top[0:10]
df_top

,Rank,Language,Nativespeakersin millions2007 (2010),Percentageof worldpopulation(2007)
0,1,Mandarin (entire branch),935 (955),14.1%
1,2,Spanish,390 (405),5.85%
2,3,English,365 (360),5.52%
3,4,Hindi[c],295 (310),4.46%
4,5,Arabic,280 (295),4.23%
5,6,Portuguese,205 (215),3.08%
6,7,Bengali,200 (205),3.05%
7,8,Russian,160 (155),2.42%
8,9,Japanese,125 (125),1.92%
9,10,Punjabi,95 (100),1.44%

### BONUS QUESTIONS

#### Scrape a certain number of tweets of a given Twitter account.

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/'

In [ ]:
# your code

#### IMDB's Top 250 data (movie name, Initial release, director name and stars) as a pandas dataframe

In [238]:
# This is the url you will scrape in this exercise 
url_imdb = 'https://www.imdb.com/chart/top'

In [239]:
# your code

response_imdb = requests.get(url_imdb)
content_imdb = response_imdb.content
print(response_imdb)

<Response [200]>

In [243]:
df_movies = pd.read_html(url_imdb)[0]
df_movies

,Unnamed: 0,Rank & Title,IMDb Rating,Your Rating,Unnamed: 4
0,NaN,1. Sueño de fuga (1994),9.2,12345678910 NOT YET RELEASED Seen,NaN
1,NaN,2. El padrino (1972),9.2,12345678910 NOT YET RELEASED Seen,NaN
2,NaN,3. Batman: El Caballero de la Noche (2008),9.0,12345678910 NOT YET RELEASED Seen,NaN
3,NaN,4. El padrino 2 (1974),9.0,12345678910 NOT YET RELEASED Seen,NaN
4,NaN,5. 12 hombres en pugna (1957),8.9,12345678910 NOT YET RELEASED Seen,NaN
...,...,...,...,...,...
245,NaN,246. Jai Bhim (2021),8.0,12345678910 NOT YET RELEASED Seen,NaN
246,NaN,247. Aladdín (1992),8.0,12345678910 NOT YET RELEASED Seen,NaN
247,NaN,248. Gandhi (1982),8.0,12345678910 NOT YET RELEASED Seen,NaN
248,NaN,249. Historias cruzadas (2011),8.0,12345678910 NOT YET RELEASED Seen,NaN
249,NaN,250. El gigante de hierro (1999),8.0,12345678910 NOT YET RELEASED Seen,NaN

In [244]:
df_movies.columns

Index(['Unnamed: 0', 'Rank & Title', 'IMDb Rating', 'Your Rating',
       'Unnamed: 4'],
      dtype='object')

In [247]:
df_movies.loc[:, ['Rank & Title', 'IMDb Rating']]

                                     Rank & Title  IMDb Rating
0                       1.  Sueño de fuga  (1994)          9.2
1                          2.  El padrino  (1972)          9.2
2    3.  Batman: El Caballero de la Noche  (2008)          9.0
3                        4.  El padrino 2  (1974)          9.0
4                 5.  12 hombres en pugna  (1957)          8.9
..                                            ...          ...
245                        246.  Jai Bhim  (2021)          8.0
246                         247.  Aladdín  (1992)          8.0
247                          248.  Gandhi  (1982)          8.0
248              249.  Historias cruzadas  (2011)          8.0
249            250.  El gigante de hierro  (1999)          8.0

[250 rows x 2 columns]

#### Movie name, year and a brief summary of the top 10 random movies (IMDB) as a pandas dataframe.

In [237]:
#This is the url you will scrape in this exercise
url = 'http://www.imdb.com/chart/top'

In [ ]:
#your code

#### Find the live weather report (temperature, wind speed, description and weather) of a given city.

In [ ]:
#https://openweathermap.org/current
city = city=input('Enter the city:')
url = 'http://api.openweathermap.org/data/2.5/weather?'+'q='+city+'&APPID=b35975e18dc93725acb092f7272cc6b8&units=metric'

In [ ]:
# your code

#### Book name,price and stock availability as a pandas dataframe.

In [ ]:
# This is the url you will scrape in this exercise. 
# It is a fictional bookstore created to be scraped. 
url = 'http://books.toscrape.com/'

In [ ]:
#your code